name: Build OpenSSL Static Library with MSVC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Perl
      run: choco install strawberryperl --pre 

    - name: Install NASM
      run: choco install nasm

    - name: Download OpenSSL source
      run: git clone https://github.com/openssl/openssl.git

    - name: Configure OpenSSL for MSVC static build
      run: |
        cd openssl
        perl Configure VC-WIN64A no-shared --prefix=%cd%\install

    - name: Build and install OpenSSL
      run: |
        cd openssl
        nmake
        nmake install

    - name: Upload OpenSSL build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openssl
        path: openssl/install
